# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar csproj y restaurar
COPY *.csproj ./
RUN dotnet restore

# Copiar todo el código
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Etapa runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Expone el puerto (Render lo usa)
EXPOSE 8080
ENTRYPOINT ["dotnet", "AmperImp.dll"]